# Generated by Django 5.2.9 on 2026-01-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tiffins/'),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
